### ISSUE TITLE
make-file for Ubuntu

### ISSUE THREAD

**Issue by nightkeo** [QuaLiKiz-group/QuaLiKiz#33]
How to compile a program on ubuntu with gfortran and gc++? Can you post a makefile? Thank you!

**Comment by Karel-van-de-Plassche** [comment]
The ifort compiler is in general way faster and free for personal use, look for example [here](https://software.intel.com/en-us/articles/intel-compilers-for-linux-and-mac-os-x-compiler-installation-help). If you want to use gfortran, you can use `src/make.inc/Makefile.archlinux` as base. Please find the wrapper you need to call to compile with mpi, usually `mpifort`. Then, put in `src/Makefile.inc` for example:

``` Makefile
QUALIKIZ=/path/to/qualikiz/root
# Underlying compiler
FC=gfortran
# Wrapper/command used to compile with Open MPI
FC_WRAPPER=mpifort
# String of text that will be put in from of the $(FC) compile option
FC_PREAMBLE=export OMPI_FC=$(FC) && 
DEBUG=
FFLAGS_GFORTRAN=$(DEBUG) -O3 -fdefault-double-8 -fdefault-real-8 -ffree-line-length-none
FFLAGS_IFORT=$(DEBUG) -O2 -real-size 64
FFLAGS=$(FFLAGS_GFORTRAN)
OPENMP_FLAGS=-fopenmp
MPI_FLAGS=-DMPI
```

Let me know if this works for you.

**Comment by Karel-van-de-Plassche** [comment]
Closing this issue as stale. There are enough examples in `src/make.inc/` to base new machine scripts on.
